name: 'ndi-2024-dev'

services:
  database:
    image: postgres:17.0
    container_name: ${COMPOSE_PROJECT_NAME}-postgresql
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: postgres-volume
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-0}
      POSTGRES_USER: ${POSTGRES_USER:-0}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-0}
    networks:
      - network

networks:
  network:
    name : ${COMPOSE_PROJECT_NAME}-network
    driver: bridge

volumes:
  postgres-volume:
    driver: local
