/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Nuit de l'info 2024 - Void LR - API Documentation
 * OpenAPI spec version: 1.0
 */

export interface LoginUserDto {
  /** The password of the user */
  password: string;
  /** The username of the user */
  username: string;
}
